# Generated by Django 5.0.6 on 2024-10-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(default='iiith', max_length=50),
            preserve_default=False,
        ),
    ]
